apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: zayjar
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: zayjar
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass ${REDIS_PASSWORD}
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
