apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zayjar
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: zayjar
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
