apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: zayjar
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: zayjar
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
