apiVersion: v1
kind: ConfigMap
metadata:
  name: zayjar-config
  namespace: zayjar
  labels:
    app.kubernetes.io/part-of: zayjar
data:
  NODE_ENV: "production"
  PORT: "8000"
  POSTGRES_DB: "zayjar_production"
  POSTGRES_USER: "postgres_admin"
  AWS_REGION: "us-east-1"
  S3_BUCKET: "zayjar-assets-production"
  TWILIO_FROM_NUMBER: "+15005550006"
  UNIFONIC_SENDER_ID: "Zayjar"
  SENDGRID_FROM_EMAIL: "noreply@zayjar.com"
